// src/products.js
const Products = [
  {
    id: 1,
    name: "Product 1",
    price: 50,
    description: "Description for Product 1",
    color: "Red",
    category: "Category A",
    image: "https://www.gonoise.com/cdn/shop/products/Side04_grande.png?v=1655378358",
  },
  {
    id: 2,
    name: "Product 2",
    price: 80,
    description: "Description for Product 2",
    color: "Blue",
    category: "Category B",
    image: "https://www.gonoise.com/cdn/shop/products/Side04_grande.png?v=1655378358",
  },
  {
    id: 3,
    name: "Product 3",
    price: 120,
    description: "Description for Product 3",
    color: "Green",
    category: "Category A",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvFFMmu1blOdMwQJGUOUiajI1wl0jiE29pAw&usqp=CAU",
  },
  {
    id: 4,
    name: "Product 4",
    price: 70,
    description: "Description for Product 4",
    color: "Yellow",
    category: "Category C",
    image: "product4.jpg",
  },
  {
    id: 5,
    name: "Product 5",
    price: 90,
    description: "Description for Product 5",
    color: "Orange",
    category: "Category B",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyfhluzBngBDiIoyb-fLaR7PRQd2OVfZByoA&usqp=CAU",
  },
  {
    id: 6,
    name: "Product 6",
    price: 60,
    description: "Description for Product 6",
    color: "Purple",
    category: "Category A",
    image: "product6.jpg",
  },
  {
    id: 7,
    name: "Product 7",
    price: 100,
    description: "Description for Product 7",
    color: "Pink",
    category: "Category C",
    image: "product7.jpg",
  },
  {
    id: 8,
    name: "Product 8",
    price: 110,
    description: "Description for Product 8",
    color: "Brown",
    category: "Category B",
    image: "product8.jpg",
  },
  {
    id: 9,
    name: "Product 9",
    price: 65,
    description: "Description for Product 9",
    color: "Black",
    category: "Category A",
    image: "product9.jpg",
  },
  {
    id: 10,
    name: "Product 10",
    price: 95,
    description: "Description for Product 10",
    color: "White",
    category: "Category C",
    image: "product10.jpg",
  },
];

export default Products;
